# Generated by Django 5.1.2 on 2024-11-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionslisting_initial_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionslisting',
            name='initial_bid',
            field=models.IntegerField(default=0),
        ),
    ]
