# Generated by Django 5.1.2 on 2024-11-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_alter_auctionslisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionslisting',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
